name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up credentials
      run: |
          cd src/app/
          touch .env
          echo OPENAPI_KEY=${{ secrets.OPENAPI_KEY }} >> .env
          cat .env
    - name: Build Docker image
      run: |
          cd src/app/
          docker build . --file Dockerfile --tag haystack-img:$(date +%s)